Traceback (most recent call last):
  File "/media/data/programming/Projects/aws/saneora/telegram_bot/__init__.py", line 1, in <module>
    from bot import start_bot
  File "/media/data/programming/Projects/aws/saneora/telegram_bot/bot.py", line 1, in <module>
    import telegram.ext
ModuleNotFoundError: No module named 'telegram'
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/nathan/Documents/saneora_env/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
