Traceback (most recent call last):
  File "/home/ec2-user/saneora/main.py", line 17, in <module>
    config.init()
AttributeError: module 'config' has no attribute 'init'
Traceback (most recent call last):
  File "/home/ec2-user/saneora/main.py", line 17, in <module>
    config.init()
AttributeError: module 'config' has no attribute 'init'
Traceback (most recent call last):
  File "/home/ec2-user/saneora/main.py", line 17, in <module>
    config.init()
AttributeError: module 'config' has no attribute 'init'
